emsize: 512
nhead: 2
nhid: 2048
nlayers: 2
dropout: 0.2
clip_norm: 1.0
epochs: 100
batch_size: 128
log_interval: 200
vocab_size: 20000
endure_times: 5
rating_reg: 0.1
context_reg: 1.0
text_reg: 1.0
item_reg: 0.1
hist_len: 10
use_feature: False
bert_like: True
seq_mode: 1
optim: "adamw"
lr: 0.001
scheduler: "steplr"
seq_prediction: True
context_prediction: True
rating_prediction: True
nextitem_prediction: True